### ISSUE TITLE
Persist session info for future connections

### ISSUE THREAD

**Issue by LynHyper** [hyprspace/hyprspace#44]
I've noticed that hyprspace seems to take the same amount of time to connect to a peer regardless of whether it's the 1st or 100th time, I'm not sure what hyprspace's node saves between sessions (or if it saves anything), but, I believe it should save some important information to speed up reconnects.

For instance, saving a few of the neighbours of a peer. This would let nodes jump straight to a peer's neighbours instead of searching towards it everytime.

There's probably a lot that could be persisted which is unique to hyprspace, but I'm struggling to think of anything. I'm interested in knowing what hyprspace does currently in more detail when it comes to authentication.

**Comment by notassigned** [comment]
It wouldn't be hard to implement this, but I think that rendezvous discovery is what is making it take a long time. If you do a direct node lookup on the DHT it is actually pretty fast, < 2 seconds. I'm experimenting with some alternative options for discovery, such as gossipsub.

**Comment by alecbcs** [comment]
Okay this might seem a little weird so bare with me but I'm going to answer your questions in reverse order :P

> I'm interested in knowing what Hyprspace does currently in more detail when it comes to authentication.

For authentication we're using libp2p's native public/private key authentication. This style of authentication is very similar to what is used in Wireguard and many other peer-to-peer encryption systems. As a very quick explanation, public and private keys are both one way functions. This means that either can be used to encrypt data but then requires the other key to decrypt the data. So when you send out a packet with Hyprspace, libp2p uses the public key of the destination peer to encrypt the data. This means that only the peer you are sending the packet to can decrypt the message since they are the only one's with the corresponding private key. 

Okay so you might be thinking, well now that's security but how do we authenticate the packet really came from my other trusted Hyprspace node. Here's the cool part! We can basically encrypt the packet twice once with the destination nodes public key and once with **our** private key. So now the node on the other end can first decrypt the packet with **our** public key to verify that we (the only person with access to our private key) encrypted the packet. It can then go ahead and decrypt the remaining packet with it's own private key to extract the unencrypted packet data. Luckily this process is all done transparently in `libp2p` so all we have to do is match the incoming sender's public key to one of the identities in our config to authenticate that the packet actually came from someone we want to receive packets from!

**Comment by alecbcs** [comment]
> I've noticed that hyprspace seems to take the same amount of time to connect to a peer regardless of whether it's the 1st or 100th time

Are you talking about reconnecting while the daemon is still running or this is the 100th time starting the daemon/interface by running `hyprspace up hs0`? In the case of the ladder we currently don't save any data on the past known address of a peer as it might have moved in the mean time and we don't want to accidentally flood some new computer/firewall with a bunch of unwarranted packets. 

I agree we should look into quicker ways to look up a peer however and that might be just as @notassigned mentioned just looking up peers directly from the DHT.

**Comment by LynHyper** [comment]
Thanks for the explanation! The PubSub method would help connection speeds (also yes, I meant running `hyprspace up hs0`), when you say "looking up peers directly from the DHT" is this in reference to the Peer Records DHT and the idea of saving non-hyprspace peers who are neighbours to the node we want?

**Comment by notassigned** [comment]
> Thanks for the explanation! The PubSub method would help connection speeds (also yes, I meant running `hyprspace up hs0`), when you say "looking up peers directly from the DHT" is this in reference to the Peer Records DHT and the idea of saving non-hyprspace peers who are neighbours to the node we want?

By 'looking up peers directly' I mean doing `KadDHT.FindPeer(context, peerID)` which returns a list of multiaddrs if the node is found. Hyprspace doesn't look up nodes directly. Instead, it provides a CID computed from the discovery string in the config and then finds other peers who are providing that string with `KadDHT.FindProviders(context, cid)` which returns a list of peers 
 with their multiaddrs who are providing the CID. This way it isn't constantly doing a peer lookup for each peer while it is not connected.

Discovery doesn't work 100% how I want it to right now but I'm debugging it and working on making it better. I'll submit a PR in a day or two.

**Comment by LynHyper** [comment]
Ah okay, I hadn't thought about large peer lists causing problems so this solution makes sense, I'll eagerly await for the PR then. Thanks for contributing to this project btw.

**Comment by alecbcs** [comment]
Hey all! Just wanted to check in here, as of v0.1.7 I believe we're now directly querying the hash table for the peer IDs and connections speeds have been greatly improved! We could probably still set the peers you've previously connected too as a form of bootstrap peers for the next time you boot up the interface but I don't know if that would cause more problems than it'd fix in the case of peers moving IPs/Ports periodically.

**Comment by LynHyper** [comment]
It's true that peers can change multiaddresses in between sessions, this might be addressed by enabling CircuitV2 for Hyprspace nodes, that way if at least one of the memorised multiaddresses work you can quickly discover the multiaddresses for other nodes through the relayed connections. Can't say if this would be any better, let me know what you think.

**Comment by LynHyper** [comment]
Being able to set Hyprspace nodes as bootstrap nodes would probably fix this without requiring anything complicated, I've already opened an issue for custom bootstrap nodes in the config, now that query times are much lower compared to when I created this issue I think I'll close this issue.
